# example netlify.toml
[build]
  command = "yarn run build"
  functions = "netlify/functions"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://nihaonow-dev-hfhga5fpgxhcedcv.uaenorth-01.azurewebsites.net/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
